export default function TermsOfServicePage() {
  const lastUpdated = "July 14, 2025"; // static date; update when terms change

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="bg-white shadow sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>

            <div className="prose prose-gray max-w-none">
              {/* Last‑updated notice */}
              <p className="text-gray-600 mb-6">Last updated: {lastUpdated}</p>

              {/* 1. Acceptance */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700 mb-4">
                By accessing or using the website, application, widgets, plug‑ins or any related services (collectively, the{" "}
                <strong>“Service”</strong>) provided by <strong>EyeCodePro</strong> ("<strong>Company</strong>", “we,” “our,” or “us”), you (<strong>“you” or “User”</strong>) acknowledge that you have read, understood, and agree to be bound by these Terms of Service (<strong>“Terms”</strong>). If you do not agree to these Terms, you must not access or use the Service.
              </p>

              {/* 2. Definitions */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">2. Definitions</h2>
              <p className="text-gray-700 mb-4">
                <strong>“Practice Data”</strong> means any data, content, claims information, custom fee schedules, or other materials that you or your end users submit to the Service.
                <br />
                <strong>“Output”</strong> means any CPT® code recommendations, rationale, analytics, reports, or other information generated by the Service.
              </p>

              {/* 3. Eligibility */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">3. Eligibility & Account Registration</h2>
              <p className="text-gray-700 mb-4">
                You represent and warrant that (i) you are at least 18&nbsp;years old, (ii) you have the authority to enter into these Terms on behalf of any clinic, practice, or other entity you represent, and (iii) all registration information you provide is accurate and complete. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
              </p>

              {/* 4. Subscription & Payment */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">4. Subscription & Payment</h2>
              <p className="text-gray-700 mb-4">
                Access to certain features of the Service may require the purchase of a subscription or payment of usage‑based fees (“<strong>Subscription</strong>”). All fees are quoted and payable in U.S.&nbsp;Dollars, are non‑refundable except as required by law, and are exclusive of all taxes. Subscriptions renew automatically unless cancelled in accordance with Section&nbsp;15 (Termination).
              </p>

              {/* 5. License to Use Service */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">5. License Grant</h2>
              <p className="text-gray-700 mb-4">
                Subject to these Terms and timely payment of applicable fees, Company grants you a limited, non‑exclusive, non‑transferable, revocable license to access and use the Service solely for your internal practice management and medical billing purposes.
              </p>

              {/* 6. Intellectual Property */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">6. Intellectual Property</h2>
              <p className="text-gray-700 mb-4">
                All right, title, and interest in and to the Service, including software, user interfaces, trademarks, logos, and aggregated analytics, are and will remain the exclusive property of Company and its licensors. Except for the limited license granted in Section&nbsp;5, no rights are granted to you under any intellectual‑property laws.
              </p>

              {/* 7. User Responsibilities */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">7. User Responsibilities</h2>
              <p className="text-gray-700 mb-4">
                You are solely responsible for (a) the accuracy and legality of all Practice Data you provide; (b) ensuring that your use of the Service complies with all applicable laws, regulations, and payer contracts, including but not limited to HIPAA, state privacy laws, and CMS guidelines; and (c) validating all Output before using it for billing, coding, or clinical decision‑making.
              </p>

              {/* 8. Access to Custom Fee Schedules */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">8. Access to Custom Fee Schedules & Practice Data</h2>
              <p className="text-gray-700 mb-4">
                To provide accurate comparisons and analytics, you authorize Company to store, process, and analyze any custom fee schedules, reimbursement contracts, or other Practice Data you upload. Company will use such data solely (i) to deliver the Service to you, (ii) to improve and maintain the Service, and (iii) in de‑identified or aggregated form for analytics and benchmarking.
              </p>

              {/* 9. Compliance & Audit Responsibility */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">9. Compliance & Audit Responsibility</h2>
              <p className="text-gray-700 mb-4">
                The Service is designed to assist with CPT® code selection and reimbursement optimization; however, <strong>Company does not guarantee compliance with payer policies or government regulations</strong>. You remain solely responsible for all claims submitted to third‑party payers, as well as for responding to any audits, overpayment demands, or compliance inquiries. Company will not be liable for fines, penalties, claw‑backs, or other losses arising from your billing activities.
              </p>

              {/* Code Selection Compliance */}
              <p className="text-gray-700 mb-4">
                EyeCodePro uses insurance fee schedules to pick between E/M codes and eye codes to maximize revenue. For compliance, charting on all exams should comply with E/M requirements. If charting meets E/M requirements then the decision on which code to pick can be based on maximizing revenue.
              </p>

              {/* 10. Medical Disclaimer */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">10. Medical Disclaimer</h2>
              <p className="text-gray-700 mb-4">
                The Output is informational only and is not intended to replace professional medical judgment, diagnosis, billing expertise, or legal counsel. Always verify codes against official CPT® guidelines and consult qualified professionals before making clinical or financial decisions.
              </p>

              {/* 11. Disclaimer of Warranties */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">11. Disclaimer of Warranties</h2>
              <p className="text-gray-700 mb-4">
                THE SERVICE IS PROVIDED ON AN “AS‑IS” AND “AS‑AVAILABLE” BASIS. COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, NON‑INFRINGEMENT, OR THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR‑FREE.
              </p>

              {/* 12. Limitation of Liability */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">12. Limitation of Liability</h2>
              <p className="text-gray-700 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY, ITS AFFILIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO THE SERVICE OR THESE TERMS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. COMPANY’S AGGREGATE LIABILITY WILL NOT EXCEED THE AMOUNTS PAID BY YOU TO COMPANY FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
              </p>

              {/* 13. Indemnification */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">13. Indemnification</h2>
              <p className="text-gray-700 mb-4">
                You agree to defend, indemnify, and hold harmless Company and its officers, directors, employees, and agents from and against all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including attorneys’ fees) arising from: (i) your use of and access to the Service; (ii) your violation of any term of these Terms; (iii) any Practice Data you submit; or (iv) your violation of any third‑party right, including any intellectual‑property or privacy right.
              </p>

              {/* 14. Modifications */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">14. Modifications to Terms or Service</h2>
              <p className="text-gray-700 mb-4">
                Company reserves the right, in its sole discretion, to modify or replace these Terms or to change, suspend, or discontinue the Service at any time. We will provide notice of material changes by posting the updated Terms on the Site or by sending you an email. Your continued use of the Service after such changes constitutes acceptance of the new Terms.
              </p>

              {/* 15. Termination */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">15. Termination & Suspension</h2>
              <p className="text-gray-700 mb-4">
                Company may suspend or terminate your access to the Service immediately, without prior notice or liability, (a) if you breach any provision of these Terms, (b) upon request by law enforcement or government agency, or (c) for scheduled or emergency maintenance. Upon termination, your right to use the Service will cease, but Sections 6, 9–13, 16–19 shall survive.
              </p>

              {/* 16. Governing Law & Dispute Resolution */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">16. Governing Law & Dispute Resolution</h2>
              <p className="text-gray-700 mb-4">
                These Terms and any dispute related to the Service will be governed by and construed in accordance with the laws of the State of Utah, without regard to its conflict‑of‑law rules. Any dispute, controversy, or claim shall be finally resolved by binding arbitration in Carbon&nbsp;County, Utah, administered by the American Arbitration Association under its Commercial Arbitration Rules.
              </p>

              {/* 17. Severability */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">17. Severability</h2>
              <p className="text-gray-700 mb-4">
                If any provision of these Terms is held to be invalid or unenforceable, such provision shall be modified to reflect the parties’ intention or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
              </p>

              {/* 18. Entire Agreement */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">18. Entire Agreement</h2>
              <p className="text-gray-700 mb-4">
                These Terms and any additional agreements expressly incorporated by reference, constitute the entire agreement between you and Company regarding the Service and supersede all prior or contemporaneous communications.
              </p>

              {/* 19. Contact Information */}
              <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">19. Contact Us</h2>
              <p className="text-gray-700 mb-4">
                For questions about these Terms, please email us at{" "}
                <a href="mailto:eyecodepro@gmail.com" className="text-blue-600 underline">eyecodepro@gmail.com</a> or mail:{" "}
                <span className="whitespace-nowrap">EyeCodePro</span>, 1600&nbsp;North&nbsp;550&nbsp;West, Price, UT&nbsp;84501.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
